name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    uses: emteknetnz/github-actions-ci-cd/.github/workflows/ci.yml@dynamic2
    with:
      extra_jobs: |
        - php: 8.1
          composer_require_extra: "silverstripe/asset-admin:1.x-dev"
          endtoend: true
          endtoend_suite: "asset-admin --config vendor/silverstripe/asset-admin/behat.yml"
        - php: 8.1
          composer_require_extra: "dnadesign/silverstripe-elemental:4.x-dev silverstripe/frameworktest:^0.4.4"
          endtoend: true
          endtoend_suite: "silverstripe-elemental --config vendor/dnadesign/silverstripe-elemental/behat.yml"
